baseURL = "https://psarka.github.io/hugo"
languageCode = "en-us"
title = "Three Thirds"
disableKinds = ["taxonomy", "taxonomyTerm"]

# Languages
defaultContentLanguage = 'en'
[languages]
    [languages.en]
        contentDir = 'content/en'
    [languages.lt]
        contentDir = 'content/lt'